name: Auto Version Bump

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      ## 1단계 version.txt읽기 + patch 자동 증가

      - name: Read and bump patch version
        id: bump
        run: |
          version=$(cat version.txt)
          echo "Current version: $version"

          IFS='.' read -ra parts <<< "$version"
          major=${parts[0]}
          minor=${parts[1]}
          patch=${parts[2]}

          patch=$((patch + 1))
          new_version="$major.$minor.$patch"

          echo "$new_version" > version.txt
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_ENV

      ## version.txt 자동 커밋 푸쉬
      - name: Commit bumped version
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          git add version.txt
          git commit -m "ci: bump version to ${{ env.new_version }}" || echo "No changes"
          git push
      

      ## tag자동 생성
      - name: tag auto create
        if: env.new_version != ''
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          
          tag="v${{ env.new_version }}"
          echo "Creae tag: $tag"
          
          git tag $tag
          git push origin $tag

      ## JAR빌드 , java 17 version
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build JAR
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
          cp app/build/libs/*.jar app.jar
          echo "JAR build complete"

      # GitHub Release 생성 + JAR 업로드
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ env.new_version }}"
          name: "v${{ env.new_version }}"
          files: |
            app.jar

      - name: Compute SHA256 for Homebrew
        run: |
          release_url="https://github.com/akrap147/algo-review-cli/releases/download/v${{ env.new_version }}/app.jar"
          curl -L -o app.jar "$release_url"
          sha256=$(shasum -a 256 app.jar | cut -d ' ' -f 1)

          echo "Computed SHA256: $sha256"
          echo "sha256=$sha256" >> $GITHUB_ENV

      # 직접 나의 homebrew repo에다가 Push를 하기 위한 clone
      - name: Clone Homebrew Tap
        run: |
         git clone https://x-access-token:${{ secrets.HOMEBREW_TAP_TOKEN }}@github.com/akrap147/homebrew-akrap.git tap

      # formula 내용 수정 (url + sha256 치환)
      - name: Update Homebrew Formula (URL + SHA256)
        run: |
          cd tap/Formula

          # URL 안전 치환
          sed -i 's|^  url ".*"|  url "https://github.com/akrap147/algo-review-cli/releases/download/v'${{ env.new_version }}'/app.jar"|' algo.rb

          # SHA256 안전 치환
          sed -i 's|^  sha256 ".*"|  sha256 "'${{ env.sha256 }}'"|' algo.rb

          echo "Updated formula:"
          cat algo.rb

      # Formula commit & push
      - name: Commit and Push Formula Update
        run: |
          cd tap
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          git add Formula/algo.rb
          git commit -m "brew: bump formula to v${{ env.new_version }}" || echo "No changes to commit"
          git push